name: JMeter Tests

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Download JMeter
      run: |
        wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.3.tgz
        tar -xzf apache-jmeter-5.4.3.tgz

    - name: Run JMeter tests
      run: apache-jmeter-5.4.3/bin/jmeter -n -t ThreadGroup.jmx -l results.jtl
