name: JMeter Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Adjust the Java version as per your requirements

      - name: Run JMeter Tests
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: 'ThreadGroup.jmx'
          outputReportsFolder: 'reports/'
          args: "--loglevel INFO -JMyProperty=Value --jmeterlogconf=log.conf"

      - name: Upload Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-reports
          path: reports/
